### PR TITLE
Separate player turn data from the game loop. 

### PR DESCRIPTION
**Pull request by travman89**
I separated the player turn data from the game loop so that it is entirely housed inside your game board class.  I updated the gameboard class to use the new version of the player_turn variable.

### CODE REVIEW

**Comment by travman89** [comment]
I haven't had time to thoroughly test the PR. Feel free to reject if you encounter any issues with it. Nice implementation of TTT 😊.

**Review by clioharp — APPROVED** [review]
This definitely makes more sense in terms of separation of concerns.

**Comment by travman89** [comment]
Hi Beau,

I had fun tinkering in your tic tac toe implementation. One thing I would
recommend is updating the readme to be clear that the implementation is
using python 3 and not 2.7. On my first attempt to run your code i was met
with a bunch of errors, and I had to install python 3 on my machine.

All the best,
-Travis

**Comment by clioharp** [comment]
Hi Travis,

My apologies about that! I know most people are still running 2.7 so I should have made that more clear in the readme. Thanks for the heads up; I updated the readme to reflect that the program needs to be run in python 3! Speaking of, I'm not sure if you saw that an independent developer is working on python 2.8, which you might be interested in, [here](https://www.naftaliharris.com/blog/why-making-python-2.8/).

Best,
Beau

**Pull request merged**
